// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKrronksh8rR1i-RszFkkDe9cRYds0V5M',
    appId: '1:222663140199:web:386ced6831807256f285c2',
    messagingSenderId: '222663140199',
    projectId: 'dash-chatapp',
    authDomain: 'dash-chatapp.firebaseapp.com',
    storageBucket: 'dash-chatapp.firebasestorage.app',
    measurementId: 'G-MY6JB2P83M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWo3SPKsYOlwcl7kTGPUcOnUWF24NHQU',
    appId: '1:222663140199:android:c6835055b7600896f285c2',
    messagingSenderId: '222663140199',
    projectId: 'dash-chatapp',
    storageBucket: 'dash-chatapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdzBaFZHRVb_IxwRlPdOiqhCT8m663zms',
    appId: '1:222663140199:ios:fb598d20cd8d3f1af285c2',
    messagingSenderId: '222663140199',
    projectId: 'dash-chatapp',
    storageBucket: 'dash-chatapp.firebasestorage.app',
    iosBundleId: 'com.example.dash',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdzBaFZHRVb_IxwRlPdOiqhCT8m663zms',
    appId: '1:222663140199:ios:fb598d20cd8d3f1af285c2',
    messagingSenderId: '222663140199',
    projectId: 'dash-chatapp',
    storageBucket: 'dash-chatapp.firebasestorage.app',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKrronksh8rR1i-RszFkkDe9cRYds0V5M',
    appId: '1:222663140199:web:c1d4d2f84c061284f285c2',
    messagingSenderId: '222663140199',
    projectId: 'dash-chatapp',
    authDomain: 'dash-chatapp.firebaseapp.com',
    storageBucket: 'dash-chatapp.firebasestorage.app',
    measurementId: 'G-YR15903Q3W',
  );
}
